analytics:
  - Analytics
  - Bayesian Statistics

serverless:
  - AWS

development:
  - Git CLI
  - Windows

webapplications:
  - Ruby on Rails
  - Flask
  - Databases

languages:
  - Python
  - Ruby
  - Javascript
  - Haskell