Analytics and Data Science:
  - Analytics
  - Bayesian Statistics

Backend Development:
  - Ruby on Rails
  - Flask
  - Databases

Coding Interview Study Guide:
  - Algorithms
  - System Design

Infrastructure:
  - AWS
  - Git CLI
  - Terraform
  - Windows

Programming Languages:
  - Haskell
  - Javascript
  - Python
  - Ruby
