Analytics and Data Science:
  - Analytics
  - Bayesian Statistics

Backend Development:
  - Databases
  - Flask  
  - Ruby on Rails

Coding Interview Study Guide:
  - Algorithms
  - System Design

Infrastructure:
  - AWS
  - Docker
  - Git CLI
  - Kubernetes
  - Terraform
  - Windows

Programming Languages:
  - Haskell
  - Javascript
  - Python
  - Ruby
