Analytics:
  - Analytics Engineering
  - Bayesian Statistics

Backend:
  - Databases
  - Flask  
  - Ruby on Rails

Coding Interview:
  - Algorithms
  - System Design

DevOps:
  - Terminal
  - AWS
  - Docker
  - Git CLI
  - Kubernetes
  - Terraform
  - Windows

Languages:
  - Haskell
  - Javascript
  - Python
  - Ruby
